---

# We could possible take a generic phpfpm_version string and map it to a dict returning the correct package string?
# eg. 5.4 = "php-fpm", 5.6 = php56u-fpm

- name: Install PHP-FPM
  yum:
    name: "{{ item }}"
    state: latest
  with_flattened:
    - phpfpm_install
    - "python-httplib2"

- name: Enable PHP-FPM
  service:
    name: php-fpm
    enabled: yes

- name: Check www.conf size
  stat:
    path:  /etc/php-fpm.d/www.conf
  register: phpfpm_www_conf

- name: Backup www.conf -> .{{ ansible_date_time.iso8601_basic_short }}
  copy:
    remote_src: True
    src: /etc/php-fpm.d/www.conf
    dest: /etc/php-fpm.d/www.conf.{{ ansible_date_time.iso8601_basic_short }}
  when: phpfpm_www_conf.stat.size > 100

- name: Blank www.conf
  copy:
    content: ; Blanked by Ansible at {{ ansible_date_time.iso8601 }}. See original at /etc/php-fpm.d/www.conf.{{ ansible_date_time.iso8601_basic_short }}
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: 0644
  when: phpfpm_www_conf.stat.size > 100

# - name: Check PHP-FPM Log Folder
#  stat:
#    path: {{ item.log_folder }}
#  register: phpfpm_log_folder
#  with_items: phpfpm_pools
#
# - name: Create PHP-FPM Log Folder
#   file:
#     path: {{ item.stat.path }}
#     owner: root
#     group:
#  with_items: fpm_log_folder.results
#  when: item.stat.exists == false

- name: Write pool configurations
  template:
    src: pool.conf.j2
    dest: /etc/php-fpm.d/{{ item.name }}.conf
    owner: root
    group: root
    mode: 0644
  with_items: phpfpm_pools
  notify: Restart PHP-FPM

# Check if Apache is installed

- name: Write Apache configuration
  template:
    src: zz-php-fpm.conf.j2
    dest: /etc/httpd/conf.d/zz-php-fpm.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Apache

# Adjust OpCache check to include other PHP versions?

- name: Configure OpCache
  include: configure_opcache.yml
  when: "'php70u-opcache' in phpfpm_install"

- name: Set php.ini options
  ini_file:
    dest: /etc/php.ini
    section: PHP
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_dict: php_fpm_ini_options
  notify: Restart PHP-FPM

- name: Install Composer
  include: composer_install.yml
  when: php_fpm_composer
