---

- name: apply common configuration to all nodes
  hosts: all
  become: yes
  vars_files:
    - magento.yml

  roles:
    - common
    - percona
    - redis
    - httpd
    - php-fpm
    - varnish

  tasks:
    - name: "Unarchive to {{ magento_root }}"
      unarchive:
        src: "{{ magento_archive }}"
        dest: "{{ magento_root }}"
        owner:  "{{ magento_user }}"
        group: "{{ magento_group }}"
        copy: no
      when: magento_archive is defined

    - name: Open HTTP/S in firewalld
      firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: yes
        state: enabled
      with_items:
        - http
        - https
      when: firewall is not defined or
            firewall
