---

phpfpm_install:
  - php70u-cli
  - php70u-fpm
  - php70u-mysqlnd
  - php70u-opcache
  - php70u-xml
  - php70u-mcrypt
  - php70u-gd
  - php70u-devel
  - php70u-intl
  - php70u-mbstring
  - php70u-bcmath
  - php70u-json


phpfpm_pools:
  - name: default
    process_user: php-fpm
    process_group: php-fpm
    listen: /tmp/$pool.socket
    listen_owner: root
    listen_group: apache
    listen_mode: "0770"
    access_log: /var/log/php-fpm/$pool-access.log
    access_format: '"%R - %u %t \"%m %r%Q%q\" %s %f %{mili}d %{kilo}M %C%% %p %P"'
    slowlog: /var/log/php-fpm/$pool-slowwwww.log
    slowlog_timeout: 15
    terminate_timeout: 30
    workers_output: "yes"
    log_errors: "yes"
    error_log: /var/log/php-fpm/$pool-errorrrrr.log
    display_errors: "off"

  - name: pool2
    process_user: php-fpm

## OpCache
memory_consumption: 32
max_accelerated_files: 1000