---

- name: Ensure Varnish repo dependencies are installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - pygpgme

- name: Add Varnish packagecloud.io repo
  template:
    src: varnish.repo.j2
    dest: /etc/yum.repos.d/varnish.repo
    owner: root
    group: root
    mode: 0644

- name: Install Varnish
  yum:
    name: varnish
    state: latest

- name: Enable Varnish
  service:
    name: varnish
    enabled: yes

- name: Write Varnish environment configuration
  template:
    src: params.j2
    dest: /etc/varnish/varnish.params
    owner: root
    group: root
    mode: 0644
  notify: Restart Varnish

- name: Write initial Varnish VCL configuration
  template:
    src: default.vcl.j2
    dest: /etc/varnish/default.vcl
    owner: root
    group: root
    mode: 0644
  notify: Restart Varnish
