---

- name: Install Redis
  yum:
    name: redis32u
    state: latest

- name: Enable Redis
  service:
    name: redis
    enabled: yes

- name: Write Redis configuration
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf
    owner: redis
    group: root
    mode: 0644
  notify: Restart Redis
