---

- name: Install Varnish 4.1 Repository
  yum:
    name: https://repo.varnish-cache.org/redhat/varnish-4.1.el7.rpm
    state: present

- name: Install Varnish 4.1
  yum:
    name: varnish
    state: latest

- name: Enable Varnish
  service:
    name: varnish
    enabled: yes

#- name: Write Redis configuration
#  template:
#    src: redis.conf.j2
#    dest: /etc/redis.conf
#    owner: redis
#    group: root
#    mode: 0644
#  notify: Restart Redis
