---

- name: Install Percona GPG Key
  rpm_key:
    key: https://www.percona.com/downloads/RPM-GPG-KEY-percona
    state: present

- name: Install Percona Repository
  yum:
    name:
    - https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    state: present
  when: rhn is not defined or
        not rhn

- name: Generate root MySQL password
  include: root_pwgen.yml
  when: mysql_root_password == ""

- name: Install Percona Server {{ mysql_version }}
  yum:
    name:
    - Percona-Server-server-{{ mysql_version | replace('.', '') }}
    - MySQL-python
    state: latest

- name: Backup my.cnf -> .{{ ansible_date_time.iso8601_basic_short }}
  copy:
    remote_src: True
    src: /etc/my.cnf
    dest: /etc/my.cnf.{{ ansible_date_time.iso8601_basic_short }}
  when: mysql_modified_cnf

- name: Write main configuration
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644
  when: mysql_modified_cnf

- name: Start and Enable Percona Server
  service:
    name: mysqld
    enabled: yes
    state: started

- name: Grab auto-generated root Percona password
  command: awk '/temporary password is generated/ {a=$NF} END{print a}' /var/log/mysqld.log
  register: mysql_password_awk
  when: mysql_version == 5.7

- name: Set auto-generated root Percona password variable {{ mysql_password_awk.stdout }}
  set_fact:
    mysql_initial_root_password: "{{ mysql_password_awk.stdout }}"
  when: mysql_version == 5.7

- name: Check for .my.cnf (is this a new install)
  stat:
    path:  /root/.my.cnf
  register: mysql_local_my_cnf

- name: Secure new MySQL Installations
  include: mysql_secure_installation.yml
  when: mysql_local_my_cnf.stat.exists == False

- name: Create MySQL users and databases
  include: users.yml
  with_items: mysql_users
  when: mysql_users is defined
