---

- name: Install pwgen
  yum:
    name: pwgen
    state: present

- name: Generate 32 character password
  command: pwgen -y1 32
  register: mysql_root_pwgen

- name: Set password variable
  set_fact:
    mysql_root_password: "{{ mysql_root_pwgen.stdout | replace(\"'\", \"-\") }}"
