---

httpd_http_port: 8080
httpd_https_port: 443
httpd_server_admin: root@localhost
httpd_server_name: false

httpd_https_protocol: all -SSLv3 -TLSv1 -TLSv1.1
httpd_https_ciphers: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256

httpd_vhost_conf_folder: vhost.d
httpd_vhost_web_folder: /var/www/vhosts

httpd_vhosts:
 - address: '*'
   name: example.com
   alias: www.example.com www1.example.com
   root: "{{ httpd_vhost_web_folder }}/example/public_html"
   phpfpm_pool: default
   https: on
   https_cert: /etc/pki/tls/certs/localhost.crt
   https_key: /etc/pki/tls/private/localhost.key
   https_proxypass: on
   proxypass_address: http://127.0.0.1:80/
