---


- name: Create lists of HTTP/S ports
  set_fact:
    httpd_http_ports: "{{ httpd_vhosts | rejectattr('http_port', 'undefined') | map(attribute='http_port') | list | unique }}"
    httpd_https_ports: "{{ httpd_vhosts | rejectattr('https_port', 'undefined') | map(attribute='https_port') | list | unique }}"

- name: Install Apache 2.4 with mod_ssl
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd
    - mod_ssl

- name: Enable Apache
  service:
    name: httpd
    enabled: yes

- name: Backup httpd.conf -> .{{ ansible_date_time.iso8601_basic_short }}
  copy:
    remote_src: True
    src: /etc/httpd/conf/httpd.conf
    dest: "/etc/httpd/conf/httpd.conf.{{ ansible_date_time.iso8601_basic_short }}"

- name: Backup ssl.conf -> .{{ ansible_date_time.iso8601_basic_short }}
  copy:
    remote_src: True
    src: /etc/httpd/conf.d/ssl.conf
    dest: "/etc/httpd/conf.d/ssl.conf.{{ ansible_date_time.iso8601_basic_short }}"

- name: Write main configuration
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0644

- name: Write SSL configuration
  template:
    src: ssl.conf.j2
    dest: /etc/httpd/conf.d/ssl.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Apache

- name: Write GZip configuration
  template:
    src: gzip.conf.j2
    dest: /etc/httpd/conf.d/gzip.conf
    owner: root
    group: root
    mode: 0644
  when: httpd_gzip
  notify: Restart Apache

# Todo: Event? Extra configs for security etc. ? Vhost?

- name: Create VHost config directory
  file:
    path: "/etc/httpd/{{ httpd_vhosts_conf_folder }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Write VHost configurations
  template:
    src: "{{ httpd_vhost_template }}"
    dest: "/etc/httpd/{{ httpd_vhosts_conf_folder }}/{{ item.filename | default(item.servername) }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items: httpd_vhosts
  notify: Restart Apache

- name: Create VHost DocumentRoot
  file:
    path: "{{ item.root | default(httpd_vhosts_web_folder + '/' + item.servername + '/public_html') }}"
    state: directory
    owner: root
    group: root
    recurse: yes
    mode: 0755
  with_items: httpd_vhosts
  notify: Restart Apache
