---

#- name: Display all variables/facts known for a host
#  debug:
#    var: hostvars[inventory_hostname]

- name: Perform CentOS/RHEL 7 Check
  fail: msg="Only supported on CentOS/RHEL 7"
  when: (ansible_distribution != "CentOS" and ansible_distribution != "RedHat") or
        (ansible_distribution_major_version != "7")

- name: Start and Enable firewalld
  service:
    name: firewalld
    enabled: yes
    state: started

- name: Install EPEL and iUS
  yum:
    name:
    - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "https://{{ {'CentOS': 'centos', 'RedHat': 'rhel'}[ansible_distribution] }}{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm"
    state: present
  register: common_repo_install
  until: common_repo_install.rc == 0
  retries: 3
  delay: 5

- name: Create Linux users
  include: users.yml
  with_items: common_users
  when: common_users is defined
