---
- name: 'Install PHP dependencies'
  yum:
    name: php-mysql,php-gd
    state: latest
  notify: restart php-fpm

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress-latest.tar.gz

- name: Extract to DocumentRoot
  unarchive:
    src: /tmp/wordpress-latest.tar.gz
    dest: /var/www/html/
    extra_opts: ['--strip-components=1']

- name: Add a wordpress user
  user:
    name: wordpress
    home: /home/wordpress/

- name: Create MySQL database
  mysql_db:
    name: wordpress
    state: present

- name: Create MySQL user
  mysql_user:
    name: username
    host: localhost
    password: password
    priv: wordpress.*:ALL
    state: present