---

- name: Install Percona Repository
  yum:
    name: http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm
    state: present

- name: Generate root MySQL password
  include: pwgen.yml
  when: mysql_root_password == ""

- name: Percona Server 5.6
  include: install_56.yml
  when: mysql_version == 5.6

- name: Percona Server 5.7
  include: install_57.yml
  when: mysql_version == 5.7

- name: Secure MySQL Installation
  include: mysql_secure_installation.yml
