---

- name: Install pwgen
  yum:
    name: pwgen
    state: present

- name: Generate 32 character password
  command: pwgen -y1 32
  register: root_pwgen

- set_fact:
    mysql_root_password: "{{ root_pwgen.stdout | replace(\"'\", \"-\") }}"

